### ISSUE TITLE
way to apply the normalizeWhitespace plugin into the addInlined calls?

### ISSUE THREAD

**Issue by hamilton** [pngwn/prism-svelte#1]
Thanks for another great Svelte tool!

I'm adding syntax highlighting to something that also uses mdsvex. In my rollup file, I am applying your `prism-svelte` plugin, which works great. I am noticing that the leading whitespace gets trimmed for the inline `script` and `style` tags in my output. I attempted to poke around the `index.js` file in this repository to see if I could find a place to hook into the [Normalize Whitespace](https://prismjs.com/plugins/normalize-whitespace/) plugin (maybe [here](https://github.com/pngwn/prism-svelte/blob/master/index.js#L141)), to no avail.

This being the source (imagine a fenced code block in mdsvex)

```svelte
<script>                    
  import whatever from 'ok';
  export let ok = 10;
</script>

<style>
div {
    color: green;
}
</style>

<div on:click={()=>{ok = 20}}>go!</div>
```

gets turned into formatting that looks like this

```svelte
<script>import whatever from 'ok';
  export let ok = 10;
</script>

<style>div {
    color: green;
}
</style>

<div on:click={()=>{ok = 20}}>go!</div>
```

Within rollup, I'm highlighting via:

```javascript
// much earlier

import Prism from 'prismjs';
import 'prism-svelte';

// much later
markdownOptions: {
  highlight: function (str, lang) {
    if (lang && lang in Prism.languages) {
      try {
        return Prism.highlight(str, Prism.languages[lang], lang);
      } catch(__) {}
    }
    return '';
  }
},
```

And applying the default `prismjs` stylesheet.

This workaround in my project's stylesheet feels acceptable in practice:

```css
.language-svelte > .token.script, .language-svelte > .token.style {
  display: block;
}

/* deal with first-line indentation issues from prism */
.language-svelte > .token.script {
  text-indent: 1.2em;
}
```

But it seems like this presumably would format as expected out of the box. Is there something I'm missing?
